### ISSUE TITLE
help with my code

### ISSUE THREAD

**Issue by projetoarduino** [AdrianCX/pico433mhz#1]
Hello, I'm using your code but it doesn't deliver an address (id), so I started working on some modifications to a code that I already used in the arduino, with this something that looks like an address, but the Anti-Code that would be the 1010 at the end or beginning of the code is not valid and I can't extract the data or button1 and button2.

Would you help me ?

https://github.com/projetoarduino/rf433-ht6p20-micropython

**Comment by AdrianCX** [comment]
Just some notes that might help you get advice.


1. You'd be better off posting on reddit and getting help from a community, if you're using raspberry pi pico - old.reddit.com/r/raspberrypipico/


For that, you could write up a page same as I did with all components and how they are wired plus code you have tried.
This is just so someone can replicate if they are curious, or to see if there's any obvious wiring issue.
I would look there to see if proper GPIO port is used, if 3.3v or 5v is wired properly, antenna, if it's soldered properly, etc.


2. What have you tried so far to debug?, 


For example how does the received signal look like? (you could plot it to see its timings and properties, one such example that does that: https://www.instructables.com/Super-Simple-Raspberry-Pi-433MHz-Home-Automation/ )


You could also use something like this which is pretty mature to figure out things: https://github.com/merbanan/rtl_433


3.  Some ideas on the project above which might help you .


- for 433 decoding/encoding I modified rpi-rf as stated in comments, so you can check that project to see if there's any updates: https://github.com/milaq/rpi-rf


- That library has a few protocols built in as defined here: https://github.com/AdrianCX/pico433mhz/blob/979b4402f97bb7bed8c8ab188bcb92bfe1285279/src/rfdevice.py#L18


- One reason to not get an id is if the protocol your hardware uses is not defined there. (just check if timings match any of the parameters there, if not experiment, they are defined a few lines above - [pulselength, then (sync/zero/one)_(high/low)](https://github.com/AdrianCX/pico433mhz/blob/979b4402f97bb7bed8c8ab188bcb92bfe1285279/src/rfdevice.py#L13)


- Another reason might just be you don't have antenna that close to the transmitting device and are not picking up signal from it but are getting data from neighbors or just noise.


- The other might be devices that emit too much (you are limited quite a bit legally), or emit more than can fit in the id (which can be corrected).


- Or perhaps 433mhz receiving device transmits data via inverted waveforms as support is described in this PR upstream: https://github.com/milaq/rpi-rf/pull/39

**Comment by AdrianCX** [comment]
Closing since no reply and this isn't a bug but more of a support request and info provided
