### ISSUE TITLE
Webserver error

### ISSUE THREAD

**Issue by TTLES33** [AdrianCX/pico433mhz#2]
After a clear copy of all files from src to pi pico W and only changing values in config.py, the webserver is throwing an error: `'NoneType' object has no attribute 'group'`, in the browser.

In the code I saw that the error is probably related to line 65 where is `m.group(1)`. m is defined as `rs.search(...`. but rs is not defined anywhere.

**Comment by AdrianCX** [comment]
Hei, there is a bug in that if URL requested does not match regex then it will fail with exception you've seen. (Also happens if non-http request)

Updated code so now you'll get proper HTTP 5xx response with full callstack and initial request.

https://github.com/AdrianCX/pico433mhz/commit/f234f8a712218e21adca7361d97ca447fecfa03c

**Comment by AdrianCX** [comment]
Bad request:
```
$ curl -v http://192.168.100.197/wrong
*   Trying 192.168.100.197:80...
* Connected to 192.168.100.197 (192.168.100.197) port 80 (#0)
> GET /wrong HTTP/1.1
> Host: 192.168.100.197
> User-Agent: curl/7.88.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 500 Internal Server Error
< Content-type: text/html
< 
Request did not match regex 'GET /(receive|send)[/]?([0-9]*)?[/]?([0-9]*)[/]?([0-9]*)? HTTP'
User either did not request HTTP, or sent to a unknown URL
Full Request: b'GET /wrong HTTP/1.1\r\nHost: 192.168.100.197\r\nUser-Agent: curl/7.88.1\r\nAccept: */*\r\n\r\n'
* Closing connection 0
```

Vs good request:

```
$ curl -v "http://192.168.100.197/send/14012112/1/350"
*   Trying 192.168.100.197:80...
* Connected to 192.168.100.197 (192.168.100.197) port 80 (#0)
> GET /send/14012112/1/350 HTTP/1.1
> Host: 192.168.100.197
> User-Agent: curl/7.88.1
> Accept: */*
> 
* HTTP 1.0, assume close after body
< HTTP/1.0 200 OK
< 
* Closing connection 0
```

**Comment by AdrianCX** [comment]
also note - it's 're' not 'rs' so if you copied you might have a typo
