### ISSUE TITLE
problem with intertechno codesend

### ISSUE THREAD

**Issue by jonesMeUp** [AdrianCX/pico433mhz#3]
A fix for rfdevice.py is needed for (at least) the 24bit rawcode.
Sorry for not making a Pull Request, but I don't have much time and didn't test my changes for other settings.
This is my change to get the missing leading Zeros in funtion txt_code(...)

```
        #rawcode = "{{0:{}b}}".format(self.tx_length + 2).format(code)[2:]
        rawcode = "{{0:0{}b}}".format(self.tx_length + 2).format(code)[2:]
```

**Comment by AdrianCX** [comment]
Awesome, thanks, ported the change.
